# File: configs/config.yaml

input_dir: "/media/lkm413/storage1/gee_embedding_download/images/Denmark/2018/"
processed_dir: "data/processed/{now}"
splits_path: "data/splits/splits_{now}.json"
output_dir: "outputs/{now}"
crs_target: "EPSG:32632"

patch_size: 512
stride: 512
batch_size: 4
num_classes: 20
input_channels: 29

model:
  encoder: resnet34
  vit_embed_dim: 512
  vit_depth: 4
  vit_heads: 8

training:
  epochs: 100
  lr: 0.0001
  weight_decay: 0.01
  use_amp: true
  early_stopping_patience: 10

loss:
  focal:
    alpha: 0.25
    gamma: 1.0
    boundary_weight: 0.2
  tversky:
    alpha: 0.3
    beta: 0.7

gradient_clipping: 1.0
