# ===== Input Data =====
input_dirs:
  - /media/lkm413/storage21/gee_embedding_download/images/Europe/2018/bands_01_22
  - /media/lkm413/storage21/gee_embedding_download/images/Europe/2018/bands_23_44
  - /media/lkm413/storage21/gee_embedding_download/images/Europe/2018/bands_45_63

input_dir: "/media/lkm413/storage11/wetland_segmentation/data"  # has subfolders inputs/ and labels/
processed_dir: data/processed/{now}
splits_path: data/splits/splits_{now}.json
output_dir: /home/lkm413/wetland_segmentation/outputs/{now}
hist_cache_dir: "/media/lkm413/storage11/wetland_segmentation/data/hist_cache"

crs_target: "EPSG:3035"

patch_size: 512
stride: 512
batch_size: 16
num_classes: 13
input_channels: 64
band_offset: 0  # Skip label band (index 1), start at band 2 (index 1 in rasterio)

# ===== Label Remapping =====
label_remap:
  0: 0
  1: 1
  2: 2
  4: 2
  6: 2
  8: 3
  9: 4
  10: 5
  12: 6
  11: 7
  13: 7
  14: 8
  15: 9
  16: 10
  17: 10
  20: 10
  21: 10
  22: 10
  18: 11
  19: 12

label_names:
  0: "No Wetland"
  1: "Rice Fields"
  2: "Riparian, fluvial and swamp forest"
  3: "Managed or grazed meadow"
  4: "Wet grasslands"
  5: "Wet heaths"
  6: "Beaches"
  7: "Inland marshes"
  8: "Open mires"
  9: "Salt marshes"
  10: "Surface water"
  11: "Saltpans"
  12: "Intertidal flats"

ignore_val: 255
nodata_val: -32768

# ===== Model =====
model:
  encoder: resnet34
  vit_embed_dim: 512
  vit_depth: 4
  vit_heads: 8
  vit_img_size: 16
  vit_patch_size: 2

# ===== Training =====
training:
  epochs: 100
  lr: 0.0001
  weight_decay: 0.01
  use_amp: false
  early_stopping_metric: loss  # or "f1"
  early_stopping_patience: 30
  deterministic: false
  scheduler: reduce_on_plateau
  scheduler_patience: 10

# ===== TensorBoard =====
tensorboard:
  restart: true
  port: 6006

# ===== Loss Function =====
loss:
  focal:
    alpha: 0.25
    gamma: 1.5
    boundary_weight: 0.4
  tversky:
    alpha: 0.2
    beta: 0.8

# ===== Gradient =====
gradient_clipping: 1.0

# ===== Splitting Strategy =====
splitting:
  background_threshold: 0.9
  train_ratio: 1
  val_ratio: 0.1
  test_ratio: 0.1
  seed: 42
  entropy_percentile:
  max_training_tiles: 10000
  stratify_by_utm: true
  utm_sampling_strategy: "equal"  # or "equal"
select:
  water_max_fraction: 0.5
  water_class: 10

# ===== Sampling =====
sampling:
  rare_class_boost: 1.5

# ===== Logging =====
logging:
  checkpoint_interval: 5
  eval_interval: 1
  save_best_only: true
  resume_from_checkpoint: null

# ===== Debugging =====
debug:
  monitor_memory: true

inference:
  label_in_first_band: true   # old script didn’t use a label band in the TIFF
  band_offset: 1
  drop_indices_after_label: [22, 45]   # drop after removing the label band
  min_valid_frac: 1.0   # e.g., require at least 1% valid pixels


