# File: configs/config.yaml
input_dir: /media/lkm413/storage1/gee_embedding_download/images/Denmark/2018/
input_dir: /media/lkm413/storage1/gee_embedding_download/images/Denmark/2018/
processed_dir: data/processed/20250715_182612
splits_path: data/splits/splits_20250715_182612.json
output_dir: outputs/20250715_182612
crs_target: EPSG:32632
patch_size: 512
batch_size: 4
num_classes: 20
input_channels: 29
model:
  encoder: resnet34
  vit_embed_dim: 512
  vit_depth: 4
  vit_heads: 8
training:
  epochs: 100
  lr: !!float 0.0001
  weight_decay: !!float 0.01
  use_amp: true
