# File: configs/config.yaml

input_dir: "/media/lkm413/storage1/gee_embedding_download/images/Denmark/2018/29b/"
processed_dir: "data/processed/20250723_200500"
splits_path: "data/splits/splits_20250723_200500.json"
output_dir: "outputs/20250723_200500"
crs_target: "EPSG:32632"

patch_size: 512
stride: 256
batch_size: 4
num_classes: 14
input_channels: 29

model:
  encoder: resnet34
  vit_embed_dim: 512
  vit_depth: 4
  vit_heads: 8
  vit_img_size: 16
  vit_patch_size: 2

training:
  epochs: 200
  lr: 0.0001
  weight_decay: 0.01
  use_amp: true
  early_stopping_metric: loss  # or "f1"
  early_stopping_patience: 30

loss:
  focal:
    alpha: 0.25
    gamma: 1.5
    boundary_weight: 0.4
  tversky:
    alpha: 0.2
    beta: 0.8

gradient_clipping: 1.0
