# File: configs/config.yaml

input_dir: "/media/lkm413/storage21/gee_embedding_download/images/Europe/2018/bands_01_22"
processed_dir: "data/processed/{now}"
splits_path: "data/splits/splits_{now}.json"
output_dir: "/home/lkm413/wetland_segmentation/outputs/{now}"
crs_target: "EPSG:3035"

patch_size: 512
stride: 512
batch_size: 16
num_classes: 13
input_channels: 22

model:
  encoder: resnet34
  vit_embed_dim: 512
  vit_depth: 4
  vit_heads: 8
  vit_img_size: 16
  vit_patch_size: 2

training:
  epochs: 200
  lr: 0.0001
  weight_decay: 0.01
  use_amp: true
  early_stopping_metric: loss  # or "f1"
  early_stopping_patience: 30
  deterministic: false
  scheduler: reduce_on_plateau
  scheduler_patience: 10

tensorboard:
  restart: true
  port: 6006

loss:
  focal:
    alpha: 0.25
    gamma: 1.5
    boundary_weight: 0.4
  tversky:
    alpha: 0.2
    beta: 0.8

gradient_clipping: 1.0

splitting:
  background_threshold: 0.9
  train_ratio: 0.5
  val_ratio: 0.1
  test_ratio: 0.1
  seed: 42
  entropy_percentile: 80        # Keep top 80% by entropy
  max_training_tiles: 5000
  stratify_by_utm: true
  utm_sampling_strategy: "equal"  # or "proportional"

sampling:
  rare_class_boost: 1.5

logging:
  checkpoint_interval: 5
  eval_interval: 1
  save_best_only: true
  resume_from_checkpoint: null

debug:
  monitor_memory: true

band_offset: 2  # Starting from band 2 = index 1 in rasterio

